<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('regions', function (Blueprint $table) {
            $table->id();
            $table->string('name')->nullable()->comment('地区名称');
            $table->string('code')->nullable()->comment('地区编码');
            $table->timestamps();
        });

        // 插入初始数据
        $regions = [
            ['name' => '印度', 'code' => 'IN'],
            ['name' => '印尼', 'code' => 'ID'],
            ['name' => '墨西哥', 'code' => 'MX'],
            ['name' => '巴西', 'code' => 'BR'],
            ['name' => '菲律宾', 'code' => 'PH'],
            ['name' => '泰国', 'code' => 'TH'],
            ['name' => '越南', 'code' => 'VN'],
            ['name' => '美国', 'code' => 'US'],
            ['name' => '加拿大', 'code' => 'CA'],
            ['name' => '英国', 'code' => 'GB'],
            ['name' => '澳大利亚', 'code' => 'AU'],
            ['name' => '法国', 'code' => 'FR'],
            ['name' => '德国', 'code' => 'DE'],
            ['name' => '俄罗斯', 'code' => 'RU'],
            ['name' => '孟加拉国', 'code' => 'BD'],
            ['name' => '尼日利亚', 'code' => 'NG'],
            ['name' => '巴基斯坦', 'code' => 'PK'],
            ['name' => '缅甸', 'code' => 'MM'],
            ['name' => '肯尼亚', 'code' => 'KE'],
            ['name' => '韩国', 'code' => 'KR'],
            ['name' => '日本', 'code' => 'JP'],
            ['name' => '新加坡', 'code' => 'SG'],
            ['name' => '马达加斯加', 'code' => 'MG'],
            ['name' => '南非', 'code' => 'ZA'],
            ['name' => '阿拉伯联合酋长国', 'code' => 'AE'],
            ['name' => '安哥拉', 'code' => 'AO'],
            ['name' => '阿富汗', 'code' => 'AF'],
            ['name' => '阿尔巴尼亚', 'code' => 'AL'],
            ['name' => '阿尔及利亚', 'code' => 'DZ'],
            ['name' => '安道尔共和国', 'code' => 'AD'],
            ['name' => '安圭拉岛', 'code' => 'AI'],
            ['name' => '安提瓜和巴布达', 'code' => 'AG'],
            ['name' => '阿根廷', 'code' => 'AR'],
            ['name' => '亚美尼亚', 'code' => 'AM'],
            ['name' => '奥地利', 'code' => 'AT'],
            ['name' => '阿塞拜疆', 'code' => 'AZ'],
            ['name' => '巴哈马', 'code' => 'BS'],
            ['name' => '巴林', 'code' => 'BH'],
            ['name' => '巴巴多斯', 'code' => 'BB'],
            ['name' => '白俄罗斯', 'code' => 'BY'],
            ['name' => '比利时', 'code' => 'BE'],
            ['name' => '伯利兹', 'code' => 'BZ'],
            ['name' => '贝宁', 'code' => 'BJ'],
            ['name' => '百慕大群岛', 'code' => 'BM'],
            ['name' => '玻利维亚', 'code' => 'BO'],
            ['name' => '博茨瓦纳', 'code' => 'BW'],
            ['name' => '文莱', 'code' => 'BN'],
            ['name' => '保加利亚', 'code' => 'BG'],
            ['name' => '布基纳法索', 'code' => 'BF'],
            ['name' => '布隆迪', 'code' => 'BI'],
            ['name' => '喀麦隆', 'code' => 'CM'],
            ['name' => '中非共和国', 'code' => 'CF'],
            ['name' => '乍得', 'code' => 'TD'],
            ['name' => '智利', 'code' => 'CL'],
            ['name' => '哥伦比亚', 'code' => 'CO'],
            ['name' => '刚果', 'code' => 'CG'],
            ['name' => '库克群岛', 'code' => 'CK'],
            ['name' => '哥斯达黎加', 'code' => 'CR'],
            ['name' => '古巴', 'code' => 'CU'],
            ['name' => '塞浦路斯', 'code' => 'CY'],
            ['name' => '捷克', 'code' => 'CZ'],
            ['name' => '丹麦', 'code' => 'DK'],
            ['name' => '吉布提', 'code' => 'DJ'],
            ['name' => '多米尼加共和国', 'code' => 'DO'],
            ['name' => '厄瓜多尔', 'code' => 'EC'],
            ['name' => '埃及', 'code' => 'EG'],
            ['name' => '萨尔瓦多', 'code' => 'SV'],
            ['name' => '爱沙尼亚', 'code' => 'EE'],
            ['name' => '埃塞俄比亚', 'code' => 'ET'],
            ['name' => '斐济', 'code' => 'FJ'],
            ['name' => '芬兰', 'code' => 'FI'],
            ['name' => '法属圭亚那', 'code' => 'GF'],
            ['name' => '加蓬', 'code' => 'GA'],
            ['name' => '冈比亚', 'code' => 'GM'],
            ['name' => '格鲁吉亚', 'code' => 'GE'],
            ['name' => '加纳', 'code' => 'GH'],
            ['name' => '直布罗陀', 'code' => 'GI'],
            ['name' => '希腊', 'code' => 'GR'],
            ['name' => '格林纳达', 'code' => 'GD'],
            ['name' => '关岛', 'code' => 'GU'],
            ['name' => '危地马拉', 'code' => 'GT'],
            ['name' => '几内亚', 'code' => 'GN'],
            ['name' => '圭亚那', 'code' => 'GY'],
            ['name' => '海地', 'code' => 'HT'],
            ['name' => '洪都拉斯', 'code' => 'HN'],
            ['name' => '匈牙利', 'code' => 'HU'],
            ['name' => '冰岛', 'code' => 'IS'],
            ['name' => '伊朗', 'code' => 'IR'],
            ['name' => '伊拉克', 'code' => 'IQ'],
            ['name' => '爱尔兰', 'code' => 'IE'],
            ['name' => '以色列', 'code' => 'IL'],
            ['name' => '意大利', 'code' => 'IT'],
            ['name' => '牙买加', 'code' => 'JM'],
            ['name' => '约旦', 'code' => 'JO'],
            ['name' => '柬埔寨', 'code' => 'KH'],
            ['name' => '哈萨克斯坦', 'code' => 'KZ'],
            ['name' => '科威特', 'code' => 'KW'],
            ['name' => '吉尔吉斯坦', 'code' => 'KG'],
            ['name' => '老挝', 'code' => 'LA'],
            ['name' => '拉脱维亚', 'code' => 'LV'],
            ['name' => '黎巴嫩', 'code' => 'LB'],
            ['name' => '莱索托', 'code' => 'LS'],
            ['name' => '利比里亚', 'code' => 'LR'],
            ['name' => '利比亚', 'code' => 'LY'],
            ['name' => '列支敦士登', 'code' => 'LI'],
            ['name' => '立陶宛', 'code' => 'LT'],
            ['name' => '卢森堡', 'code' => 'LU'],
            ['name' => '马拉维', 'code' => 'MW'],
            ['name' => '马来西亚', 'code' => 'MY'],
            ['name' => '马尔代夫', 'code' => 'MV'],
            ['name' => '马里', 'code' => 'ML'],
            ['name' => '马耳他', 'code' => 'MT'],
            ['name' => '毛里求斯', 'code' => 'MU'],
            ['name' => '摩尔多瓦', 'code' => 'MD'],
            ['name' => '摩纳哥', 'code' => 'MC'],
            ['name' => '蒙古', 'code' => 'MN'],
            ['name' => '蒙特塞拉特岛', 'code' => 'MS'],
            ['name' => '摩洛哥', 'code' => 'MA'],
            ['name' => '莫桑比克', 'code' => 'MZ'],
            ['name' => '纳米比亚', 'code' => 'NA'],
            ['name' => '瑙鲁', 'code' => 'NR'],
            ['name' => '尼泊尔', 'code' => 'NP'],
            ['name' => '荷兰', 'code' => 'NL'],
            ['name' => '新西兰', 'code' => 'NZ'],
            ['name' => '尼加拉瓜', 'code' => 'NI'],
            ['name' => '尼日尔', 'code' => 'NE'],
            ['name' => '朝鲜', 'code' => 'KP'],
            ['name' => '挪威', 'code' => 'NO'],
            ['name' => '阿曼', 'code' => 'OM'],
            ['name' => '巴拿马', 'code' => 'PA'],
            ['name' => '巴布亚新几内亚', 'code' => 'PG'],
            ['name' => '巴拉圭', 'code' => 'PY'],
            ['name' => '秘鲁', 'code' => 'PE'],
            ['name' => '波兰', 'code' => 'PL'],
            ['name' => '法属玻利尼西亚', 'code' => 'PF'],
            ['name' => '葡萄牙', 'code' => 'PT'],
            ['name' => '波多黎各', 'code' => 'PR'],
            ['name' => '卡塔尔', 'code' => 'QA'],
            ['name' => '罗马尼亚', 'code' => 'RO'],
            ['name' => '圣卢西亚', 'code' => 'LC'],
            ['name' => '圣文森特岛', 'code' => 'VC'],
            ['name' => '圣马力诺', 'code' => 'SM'],
            ['name' => '圣多美和普林西比', 'code' => 'ST'],
            ['name' => '沙特阿拉伯', 'code' => 'SA'],
            ['name' => '塞内加尔', 'code' => 'SN'],
            ['name' => '塞舌尔', 'code' => 'SC'],
            ['name' => '塞拉利昂', 'code' => 'SL'],
            ['name' => '斯洛伐克', 'code' => 'SK'],
            ['name' => '斯洛文尼亚', 'code' => 'SI'],
            ['name' => '所罗门群岛', 'code' => 'SB'],
            ['name' => '索马里', 'code' => 'SO'],
            ['name' => '西班牙', 'code' => 'ES'],
            ['name' => '斯里兰卡', 'code' => 'LK'],
            ['name' => '苏丹', 'code' => 'SD'],
            ['name' => '苏里南', 'code' => 'SR'],
            ['name' => '斯威士兰', 'code' => 'SZ'],
            ['name' => '瑞典', 'code' => 'SE'],
            ['name' => '瑞士', 'code' => 'CH'],
            ['name' => '叙利亚', 'code' => 'SY'],
            ['name' => '塔吉克斯坦', 'code' => 'TJ'],
            ['name' => '坦桑尼亚', 'code' => 'TZ'],
            ['name' => '多哥', 'code' => 'TG'],
            ['name' => '汤加', 'code' => 'TO'],
            ['name' => '特立尼达和多巴哥', 'code' => 'TT'],
            ['name' => '突尼斯', 'code' => 'TN'],
            ['name' => '土耳其', 'code' => 'TR'],
            ['name' => '土库曼斯坦', 'code' => 'TM'],
            ['name' => '乌干达', 'code' => 'UG'],
            ['name' => '乌克兰', 'code' => 'UA'],
            ['name' => '乌拉圭', 'code' => 'UY'],
            ['name' => '乌兹别克斯坦', 'code' => 'UZ'],
            ['name' => '委内瑞拉', 'code' => 'VE'],
            ['name' => '也门', 'code' => 'YE'],
            ['name' => '南斯拉夫', 'code' => 'YU'],
            ['name' => '津巴布韦', 'code' => 'ZW'],
            ['name' => '扎伊尔', 'code' => 'ZR'],
            ['name' => '赞比亚', 'code' => 'ZM'],
            ['name' => '克罗地亚', 'code' => 'HR'],
            ['name' => '塞尔维亚', 'code' => 'RS'],
            ['name' => '梵蒂冈', 'code' => 'VA'],
            ['name' => '北马其顿', 'code' => 'MK'],
            ['name' => '黑山', 'code' => 'ME'],
            ['name' => '波黑', 'code' => 'BA'],
        ];

        DB::table('regions')->insert($regions);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('regions');
    }
};
